[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Martin Frost <frost@ceri.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
